apiVersion: v1
kind: ConfigMap
metadata:
  name: splitsmart-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/splitsmart"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
